import React from "react";
import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTRmiwCEe9fWLlPuOYV9I4lz2tj-ga-zCDIFNMlrsmviTIDfPF6-WILy8C8KuVN",
    title: "Sunset Serenity",
    star: <AiFillStar className="rating-star" />,
    reviews: "(56 reviews)",
    prevPrice: "Rs. 2,00,000",
    newPrice: "170000",
    category: "Landscape Painting",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQZFBQTjAIQyRt86uf6DlmggHXqle6s8b3kN-hjYklFf6lERIDpw3mse2cDua_B",
    title: "Abstract Dreams",
    star: <AiFillStar className="rating-star" />,
    reviews: "(87 reviews)",
    prevPrice: "Rs. 1,50,000",
    newPrice: "150000",
    category: "Abstract Art",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRSS37HO3sAk-uZn0rmgjxHZcnZ0lZhDropPAU4MWDikov7MsJa7l-uhVXYLlhr",
    title: "Nature's Beauty",
    star: <AiFillStar className="rating-star" />,
    reviews: "(42 reviews)",
    prevPrice: "Rs. 1,60,000",
    newPrice: "150000",
    category: "Floral Painting",
  },
  {
    img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQIwOT4aDFC5ebMHMzDaSLi8u_LyooUDI7KBT_xU6htKSsh5RRHHrnkdGeF5--r",
    title: "Cityscape Vibes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(98 reviews)",
    prevPrice: "Rs. 2,20,000",
    newPrice: "195000",
    category: "Cityscape Art",
  },
  {
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSg-dkkA8zqE10-sHEFE5M_o1bpCizbGfdehYC21th1K67NdOuSRruaA1Zkos0W",
    title: "Mystic Mountains",
    star: <AiFillStar className="rating-star" />,
    reviews: "(75 reviews)",
    prevPrice: "Rs. 1,70,000",
    newPrice: "170000",
    category: "Mountain Landscape",
  },
  {
    img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQ-49it5PkspL0ifSAGgsn50b1OqWpiUhzV6uIXizfV-pr_Y-xgoSkYshEL1OWE",
    title: "Ocean Dreams",
    star: <AiFillStar className="rating-star" />,
    reviews: "(63 reviews)",
    prevPrice: "Rs. 1,90,000",
    newPrice: "160000",
    category: "Seascape Art",
  },
  {
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcR1szWRU0qYLg7JW_opbKx1ahP2lV9V3ThPr8vTtrbaOtLEsjRfAp8yCBbIrZYw",
    title: "Vintage Elegance",
    star: <AiFillStar className="rating-star" />,
    reviews: "(115 reviews)",
    prevPrice: "Rs. 1,75,000",
    newPrice: "150000",
    category: "Vintage Art",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0Oiqc_o_bTu9Hftxp-hIxzXLIQDhmDzW2fDfvttqSfAYepbS9xm06MGmcz35u",
    title: "Abstract Fusion",
    star: <AiFillStar className="rating-star" />,
    reviews: "(54 reviews)",
    prevPrice: "Rs. 2,10,000",
    newPrice: "170000",
    category: "Contemporary Art",
  },
  {
    img: "https://www.bing.com/th?id=OIP.XU0rPNosSA27Rr2IcAhi0AHaHa&w=92&h=100&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    title: "Urban Reflections",
    star: <AiFillStar className="rating-star" />,
    reviews: "(69 reviews)",
    prevPrice: "Rs. 1,95,000",
    newPrice: "170000",
    category: "Urban Art",
  },
  {
    img: "https://www.bing.com/th?id=OIP.4JbPFotwTR7AxGBZIBeigAHaF4&w=233&h=185&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    title: "Wildlife Safari",
    star: <AiFillStar className="rating-star" />,
    reviews: "(82 reviews)",
    prevPrice: "Rs. 1,85,000",
    newPrice: "160000",
    category: "Wildlife Painting",
  },
  {
    img: "https://www.bing.com/th?id=OIP.O68q2rin9g5Hgzx32zM9_wHaFj&w=203&h=185&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    title: "Sunrise Bliss",
    star: <AiFillStar className="rating-star" />,
    reviews: "(44 reviews)",
    prevPrice: "Rs. 2,30,000",
    newPrice: "195000",
    category: "Sunrise Art",
  },
  {
    img: "https://www.bing.com/th?id=OIP.J3AuWx-IWPIUMDfa1h4-cwHaJQ&w=155&h=185&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    title: "Floral Delight",
    star: <AiFillStar className="rating-star" />,
    reviews: "(77 reviews)",
    prevPrice: "Rs. 1,80,000",
    newPrice: "150000",
    category: "Floral Painting",
  },
  {
    img: "https://www.bing.com/th?id=OIP.XNepcwetqdgYxFENK8N0sgHaFo&w=242&h=185&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    title: "Mountain Majesty",
    star: <AiFillStar className="rating-star" />,
    reviews: "(51 reviews)",
    prevPrice: "Rs. 1,70,000",
    newPrice: "170000",
    category: "Mountain Landscape",
  },
  {
    img: "https://www.bing.com/th?id=OIP.9eXHduuD5XWEejp8B4H6NwHaHX&w=185&h=185&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    title: "Abstract Creation",
    star: <AiFillStar className="rating-star" />,
    reviews: "(93 reviews)",
    prevPrice: "Rs. 2,15,000",
    newPrice: "195000",
    category: "Abstract Art",
  },
  {
    img: "https://www.bing.com/th?id=OIP.Tv0zcXSal_6QsxPsf8ah5wHaFj&w=197&h=185&c=8&rs=1&qlt=90&o=6&dpr=1.3&pid=3.1&rm=2",
    title: "Coastal Serenity",
    star: <AiFillStar className="rating-star" />,
    reviews: "(68 reviews)",
    prevPrice: "Rs. 1,75,000",
    newPrice: "150000",
    category: "Seascape Art",
  },

];
export default data;
